language: python

# sudo false implies containerized builds
sudo: false

os:
  - linux

python:
  - "3.7"
  - "3.8"

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests

env:
  # build analysis
  - TASK=build

addons:
  apt:
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - gcc-4.9
      - g++-4.9

before_install:
  - source scripts/travis/travis_setup_env.sh

install:
  - source scripts/travis/setup.sh

script:
  - pytest tests
  - pylint pyeit

cache:
  directories:
    - ${HOME}/.cache/usr

before_cache:
  - scripts/travis/travis_before_cache.sh

after_failure:
  - scripts/travis/travis_after_failure.sh

notifications:
  email:
    on_success: change
    on_failure: always

